# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8.0
language: objective-c
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
- xctool -workspace Example/LPDNetworkingKit.xcworkspace -scheme LPDNetworkingKit-Example -sdk iphonesimulator9.3
- pod lib lint --allow-warnings
